# yaml-language-server: $schema=https://raw.githubusercontent.com/aws-cloudformation/cloudformation-cli/master/schema/provider.definition.schema.v1.json
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront Distribution and S3 Bucket for Idits Drive Frontend (dev.idit.photos)'

Parameters:
  DomainName:
    Type: String
    Default: dev.idit.photos
    Description: Custom domain name for CloudFront distribution
  
  CertificateArn:
    Type: String
    Default: ''
    Description: ACM Certificate ARN for HTTPS (leave empty for CloudFront default certificate)
  
  BucketName:
    Type: String
    Default: idits-drive-frontend-dev
    Description: S3 bucket name for static assets

Resources:
  # S3 Bucket for static hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - !Sub 'https://${DomainName}'
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3600

  # CloudFront Origin Access Identity (for S3 bucket access)
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${BucketName}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub 'CloudFront distribution for ${DomainName}'
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        PriceClass: PriceClass_100
        Aliases:
          !If
            - HasCertificate
            - - !Ref DomainName
            - !Ref "AWS::NoValue"
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
            Headers:
              - CloudFront-Forwarded-Proto
              - Authorization
        CacheBehaviors:
          # Cache static assets for longer
          - PathPattern: '_next/static/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            MinTTL: 31536000
            DefaultTTL: 31536000
            MaxTTL: 31536000
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          # Don't cache HTML files
          - PathPattern: '*.html'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          !If
            - HasCertificate
            - AcmCertificateArn: !Ref CertificateArn
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            - CloudFrontDefaultCertificate: true

  # Bucket Policy to allow CloudFront OAI access  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontOAI
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOriginAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

Conditions:
  HasCertificate:
    !Not [!Equals [!Ref CertificateArn, '']]
  UseCustomDomain:
    !Equals [!Ref CertificateArn, '']
    # Only use custom domain if certificate is provided

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  
  DistributionDomain:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomain'
  
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  WebsiteURL:
    Description: Website URL
    Value: !Sub 'https://${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

